[project]
name = "furry_detector"
version = "1.0.0"
license = "MIT"
readme = "README.md"
python = "^3.8"
homepage = "https://github.com/ZenithO-o/FurryDetector"
repository = "https://github.com/ZenithO-o/FurryDetector"

[tool.black]
line-length = 88
target_version = ["py36", "py37", "py38"]
